name: protennisfitness
description: ProTennisFitness.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter         # Add this line

  cupertino_icons: ^1.0.4
  # carousel_pro: ^1.0.0
  carousel_nullsafety: ^0.1.1
  page_transition: ^2.0.5
  flutter_slidable: ^1.2.0
  fluttertoast: ^8.0.9
  #intl_phone_number_input: ^0.7.0+2
  flutter_spinkit: ^5.1.0
  intl: ^0.17.0
  mvc_pattern: ^8.9.0
  shared_preferences: ^2.0.6
  numberpicker: ^2.1.1
  http: ^0.13.4
  global_configuration: ^2.0.0-nullsafety.1
  cached_network_image: ^3.2.1
  flutter_cache_manager: ^3.3.0
  video_player: ^2.3.0
  flutter_html: ^2.2.1
  url_launcher: ^6.0.20
  # flutter_stripe: ^3.3.0

  webview_flutter: ^2.0.4
  
  in_app_purchase: ^3.0.7
  pay_ios: ^1.0.7

  # pay: ^1.0.5 - precisa de ter conta apple no projecto
  #stripe_payment: ^1.1.4
  flutter_credit_card: ^3.0.1

dependency_overrides:
  platform: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_launcher_icons: "^0.7.3"

# flutter_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/icon.png"

# module:
#   androidX: true

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/cfg/
    - assets/icon/
    - assets/quick_home_workout/
    - assets/slider/
    - assets/flat_abs_workout/
    - assets/workout/
    - assets/popular_workout/
    - assets/trainer/
    - assets/health_tips/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/inter/Inter-Regular.ttf
        - asset: fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: fonts/inter/Inter-Light.ttf
          weight: 300
flutter_intl:
  enabled: true
